# Generated by Django 5.1.4 on 2025-01-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeCatalogAPP', '0003_user_is_active_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
