# Generated by Django 5.1.4 on 2025-02-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeCatalogAPP', '0004_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
